//
// Created by machm on 20.12.2023.
//

#ifndef HANGMAN_SERVER_CONFIG_H
#define HANGMAN_SERVER_CONFIG_H

#define BUFFER_SIZE 2048
#define WORD_POOL {"AUTO", "VLAK", "PONORKA", "KOTVA", "MRAK", "VRTULE"}
//#define WORD_POOL {"ANAKONDA"}
#define MAX_WRONG_MSGS 3
#define NAME_LENGHT 15
#define STARTING_HP 5
#define STARTING_HP_STRING "5"
#define PING_PERIOD 5
//#define MISSED_PING_TO_TEMP_DISCONNECT 1
#define MISSED_PING_TO_FULL_DISCONNECT 4

#endif //HANGMAN_SERVER_CONFIG_H
